// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqvayhyvfdxjkngwzoek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxdmF5aHl2ZmR4amtuZ3d6b2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODQ4NjYsImV4cCI6MjA2NTg2MDg2Nn0.Q1FIXyU28luKq1R5KIl9JGaqf4tOoIhdd2cgzMI4zvU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);