
import jsPDF from 'jspdf';
import { formatPrice } from './formatters';

export const generateQuotePDF = (data: any, quoteData: any) => {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(20);
  doc.setTextColor(34, 197, 94); // Green color
  doc.text('PndaSolar System Quote', 20, 30);
  
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Generated on: ${new Date().toLocaleDateString('en-NG')}`, 20, 45);
  
  // System Overview
  doc.setFontSize(16);
  doc.text('System Overview', 20, 65);
  
  let yPos = 80;
  
  // Appliances section
  doc.setFontSize(14);
  doc.text('Selected Appliances:', 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  data?.appliances?.forEach((appliance: any, index: number) => {
    doc.text(`• ${appliance.quantity}x ${appliance.name} (${appliance.hoursPerDay}h/day)`, 25, yPos);
    yPos += 8;
  });
  
  yPos += 10;
  
  // Components section
  doc.setFontSize(14);
  doc.text('System Components:', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  doc.text('Inverter:', 20, yPos);
  doc.text(data?.inverter?.model_name || 'Not selected', 70, yPos);
  doc.text(formatPrice(quoteData.inverter_cost), 150, yPos);
  yPos += 12;
  
  doc.text('Battery:', 20, yPos);
  doc.text(data?.battery?.configuration || 'Not selected', 70, yPos);
  doc.text(formatPrice(quoteData.battery_cost), 150, yPos);
  yPos += 12;
  
  doc.text('Solar Panels:', 20, yPos);
  doc.text(`${data?.panels?.panels?.recommended_quantity}x ${data?.panels?.panels?.model_name}` || 'Not selected', 70, yPos);
  doc.text(formatPrice(quoteData.panel_cost), 150, yPos);
  yPos += 12;
  
  doc.text('Location:', 20, yPos);
  doc.text(data?.panels?.state || 'Not selected', 70, yPos);
  yPos += 20;
  
  // Pricing breakdown
  doc.setFontSize(14);
  doc.text('Pricing Breakdown:', 20, yPos);
  yPos += 15;
  
  doc.setFontSize(12);
  doc.text('Subtotal:', 20, yPos);
  doc.text(formatPrice(quoteData.subtotal), 150, yPos);
  yPos += 12;
  
  doc.text('Installation & Setup (15%):', 20, yPos);
  doc.text(formatPrice(quoteData.installation_cost), 150, yPos);
  yPos += 20;
  
  // Total
  doc.setFontSize(16);
  doc.setTextColor(34, 197, 94);
  doc.text('Total Investment:', 20, yPos);
  doc.text(formatPrice(quoteData.total_cost), 150, yPos);
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by PndaSolar - Your trusted solar energy partner', 20, 280);
  doc.text('Visit us at: https://pndasolar.com', 20, 290);
  
  // Save the PDF
  doc.save(`PndaSolar-Quote-${new Date().toISOString().split('T')[0]}.pdf`);
};
